[package]
name = "rezk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
regex-syntax = "0.6"
enum-utils = "0.1"
enum-display-derive = "0.1"
