[package]
name = "rezk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashconsing = { git = "https://github.com/alex-ozdemir/hashconsing.git", branch = "phash"}
structopt = "0.3"
ark-ec = { version = "^0.3.0" }
ark-ff = { version = "^0.3.0", features=["std"] }
ark-std = "^0.3.0"
ark-relations = "^0.3.0"
ark-r1cs-std = { version = "^0.3.0", features = ["std"] }
ark-bls12-381 = "^0.3.0"
ark-pallas = "^0.3.0"
regex-syntax = "0.6"
itertools = "0.10"
nova-snark = "0.8.1" # backend
bellperson = { version = "0.22", default-features = false }
pasta_curves = { version = "0.4.0", features = ["repr-c"] }
ff = "0.12.0"
ark-poly = { version = "^0.3.0", default-features = false }
#ark-test-curves = { version = "^0.3.0", default-features = false, features
#= ["bls12_381_scalar_field", "bls12_381_curve", "mnt4_753_scalar_field"] }


