version: 2.1

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"